# Generated by Django 5.2.17 on 2026-09-17 08:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the leather article (e.g., Classic Leather Wallet)', max_length=200)),
                ('category', models.CharField(choices=[('Wallets', 'Wallets'), ('Belts', 'Belts'), ('Handbags', 'Handbags'), ('Card Holders', 'Card Holders'), ('Keychains', 'Keychains'), ('Pouches', 'Pouches'), ('Leather Covers', 'Leather Covers')], help_text='Product category for filtering and templates', max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the leather product, dimensions, and craft details')),
                ('material', models.CharField(help_text='Primary leather type or material grade (e.g., Full Grain Leather)', max_length=150)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base starting price in INR (₹)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('image', models.ImageField(blank=True, help_text='High-resolution product showcase image', null=True, upload_to='articles/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when article template was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when article template was last modified')),
            ],
            options={
                'verbose_name': 'Leather Article',
                'verbose_name_plural': 'Leather Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
