# Generated by Django 5.2.17 on 2026-09-22 06:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Custom name for this design (e.g., Classic Brown Wallet)', max_length=200)),
                ('leather_type', models.CharField(choices=[('Full Grain Leather', 'Full Grain Leather'), ('Top Grain Leather', 'Top Grain Leather'), ('Genuine Leather', 'Genuine Leather'), ('Suede Leather', 'Suede Leather')], default='Full Grain Leather', help_text='Grade of leather chosen for fabrication', max_length=50)),
                ('leather_color', models.CharField(choices=[('Black', 'Black'), ('Brown', 'Brown'), ('Tan', 'Tan'), ('Dark Brown', 'Dark Brown'), ('Red', 'Red'), ('Blue', 'Blue')], default='Brown', help_text='Primary leather dye / color', max_length=30)),
                ('leather_finish', models.CharField(choices=[('Matte', 'Matte'), ('Smooth', 'Smooth'), ('Textured', 'Textured'), ('Glossy', 'Glossy')], default='Matte', help_text='Surface texture and sheen treatment', max_length=30)),
                ('width', models.DecimalField(decimal_places=2, help_text='Article width in centimeters', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('500.0'))])),
                ('height', models.DecimalField(decimal_places=2, help_text='Article height in centimeters', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('500.0'))])),
                ('depth', models.DecimalField(decimal_places=2, help_text='Article depth in centimeters', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('500.0'))])),
                ('stitching_color', models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Brown', 'Brown'), ('Tan', 'Tan'), ('Red', 'Red')], default='Brown', help_text='Color of the edge and structural stitching', max_length=30)),
                ('custom_text', models.CharField(blank=True, default='', help_text='Optional embossed text or brand name', max_length=100)),
                ('font', models.CharField(choices=[('Classic', 'Classic'), ('Modern', 'Modern'), ('Elegant', 'Elegant'), ('Bold', 'Bold')], default='Classic', help_text='Typography style for embossed custom text', max_length=30)),
                ('text_size', models.PositiveIntegerField(choices=[(12, '12 pt'), (14, '14 pt'), (16, '16 pt'), (18, '18 pt'), (20, '20 pt'), (24, '24 pt'), (28, '28 pt'), (32, '32 pt')], default=18, help_text='Font size in points for custom text', validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(32)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when design was configured')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when design was last modified')),
                ('article', models.ForeignKey(help_text='The base leather article template', on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='articles.article')),
                ('user', models.ForeignKey(help_text='The artisan/entrepreneur who created this design', on_delete=django.db.models.deletion.CASCADE, related_name='designs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Design',
                'verbose_name_plural': 'Custom Designs',
                'ordering': ['-created_at'],
            },
        ),
    ]
